### PR TITLE
Ensure backwards compatibility with plugin format from 0.4.1

### PR DESCRIPTION
**Pull request by qvicksilver**

### CODE REVIEW

**Comment by sschuberth** [comment]
Thanks for the fix! Unfortunately, it's a bit hard to see through the real changes in the commit due to the unnecessary indentation / formatting changes. Would you mind removing these from the commit so that reviewers can focus on the important stuff?

**Comment by dblock** [comment]
https://github.com/dblock/jenkins-ansicolor-plugin/pull/62/files?w=1 makes it cleaner FYI

**Comment by dblock** [comment]
I am going to merge this, looks reasonable to me.

**Comment by sschuberth** [comment]
> https://github.com/dblock/jenkins-ansicolor-plugin/pull/62/files?w=1 makes it cleaner FYI

Ah, that's a good tip! Thanks.

**Pull request merged**
