### PR TITLE
[JENKINS-37284] Added custom pipeline step

### PR DESCRIPTION
**Pull request by cpoenisch**
Relates to issue #80 and [JENKINS-37284](https://issues.jenkins-ci.org/browse/JENKINS-37284).

Provides the ability to use a custom pipeline step without allocating a node and a separate build wrapper.

Instead of 

```
node {
  wrap([$class: 'AnsiColorBuildWrapper', 'colorMapName': 'XTerm']) {
    <something that outputs ansi colored stuff>
  }
}
```

also following pipeline syntax can be used

```
ansiColor('xterm') {
  <something that outputs ansi colored stuff>
}
```

### CODE REVIEW

**Comment by dblock** [comment]
Looks good to me, @ejelly @qvicksilver also take a look pls?
Needs CHANGELOG and README updates, please.

**Comment by dblock** [comment]
Looks great, merging.

@cpoenisch Want to help out with the next release?

**Comment by lsglick** [comment]
Hi @dblock! Any idea when we'll see this in a new release? Thanks!

**Comment by dblock** [comment]
I was hoping someone else can do it, see https://github.com/dblock/jenkins-ansicolor-plugin/issues/75. Add your +1.

**Comment by eyelock** [comment]
Also added my +1 to this, having the coloring in a non-node context would be pretty cool.  Would love to do a release but pretty new to all this.

**Comment by dblock** [comment]
I tried to make a release, but right now maven.jenkins-ci.org 8081 seems MIA :( 

Will try later ...

**Comment by dblock** [comment]
OK, that host was discontinued, see https://twitter.com/jenkinsci/status/800526772773142530
I updated the pom.xml with the correct URL in https://github.com/dblock/jenkins-ansicolor-plugin/commit/38ae5ec82cf1125e260a79758c48d54fa0bb7331

**Comment by dblock** [comment]
This was finally released in 0.4.3. Thanks for your patience.

**Pull request merged**
