### PR TITLE
Some cleanups to make the code more readable

### PR DESCRIPTION
**Pull request by sschuberth**

### CODE REVIEW

**Comment by dblock** [comment]
I like it, merging. Thanks.

**Comment by sschuberth** [comment]
Thanks for merging! Can we expect a new release soon with the recent changes?

**Comment by ejelly** [comment]
I'd personally like to get the default colors working for continuous output on Firefox/Chrome before releasing.
Speaking of which, let me look at that today.

**Comment by sschuberth** [comment]
Right, I already forgot about that one ;-)

**Pull request merged**
