### PR TITLE
Improved snippet generation

### PR DESCRIPTION
**Pull request by qvicksilver**

### CODE REVIEW

**Comment by dblock** [comment]
Should still have a CHANGELOG entry.

**Comment by dblock** [comment]
Sorry just seeing this. Squash the commits please?

**Comment by qvicksilver** [comment]
Had also forgotten about this... But now the commits are squashed!

**Comment by dblock** [comment]
Merged, thanks.

**Comment by dblock** [comment]
This was finally released in 0.4.3. Thanks for your patience.

**Pull request merged**
